<script setup lang="ts">
  import { Card } from '@/components/ui/card'
  import { DotSeparator } from '@/components/ui/separator'
  import { useLockerRoomStore } from '@/stores/locker-room/locker-room.store'
  import { storeToRefs } from 'pinia'
  import { computed, onMounted, ref } from 'vue'
  import { API } from '@/services'
  import { toast } from 'vue-sonner'
  import { Tooltip, TooltipProvider, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip'
  import { Button } from '@/components/ui/button'
  import { ButtonGroup } from '@/components/ui/button-group'
  import { Input } from '@/components/ui/input'
  import { Spinner } from '@/components/ui/spinner'
  import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuTrigger
  } from '@/components/ui/dropdown-menu'
  import { PLACEHOLDER_IMAGE } from '@/helpers/imageHelper'
  import {
    Check,
    X,
    Calendar,
    ShoppingBag,
    InfoIcon,
    Share2,
    Loader2,
    FileDown,
    MoreVertical,
    Trash2
  } from 'lucide-vue-next'
  import { timeAgo, downloadFromUrl } from '@/lib/utils'
  import AvatarQueue from '../ui/avatar-queue/AvatarQueue.vue'
  import ShareUrlTooltip from '@/components/shared/ShareUrlTooltip.vue'
  import EmptyState from '@/components/shared/EmptyState.vue'
  import { useProfileStore } from '@/stores/profile/profile.store'
  import { confirmDialog } from '@/lib/confirm-dialog'
  import type { Collection } from '@/services/lockers/types'
  import {
    locker_name_placeholder,
    locker_designs_count,
    locker_auto_generated,
    locker_auto_generated_tooltip,
    locker_delete_collection_confirm,
    locker_action_cannot_undo,
    msg_failed_to_generate_share_url,
    time_ago_just_now,
    time_ago_seconds,
    time_ago_seconds_plural,
    time_ago_minutes,
    time_ago_minutes_plural,
    time_ago_hours,
    time_ago_hours_plural,
    time_ago_days,
    time_ago_days_plural,
    time_ago_yesterday,
    time_ago_months,
    time_ago_months_plural,
    time_ago_years,
    time_ago_years_plural
  } from '@/paraglide/messages'
  type SortOption = 'lastModified' | 'alphabetical' | 'createdDate'
  type CollectionFilter = 'all' | 'autoGenerated' | 'custom'

  const props = withDefaults(
    defineProps<{
      search?: null | string
      sort?: SortOption
    }>(),
    {
      search: null,
      sort: 'lastModified'
    }
  )

  const emit = defineEmits([
    'select-collection',
    'edit-locker',
    'copy-locker',
    'open-locker',
    'open-collection'
  ])
  const lockerRoomStore = useLockerRoomStore()
  const profileStore = useProfileStore()
  const isCreatingCollection = ref<boolean>(false)
  const collectionFilter = ref<CollectionFilter>('all')
  const { isLoading, collections } = storeToRefs(lockerRoomStore)
  const locale = computed(() => profileStore.currentLocale || 'en')
  const shareTooltipOpen = ref<Record<number, boolean>>({})
  /** Same-tick URL from last share response so the tooltip can open with `!!shareUrl` before the list re-renders. */
  const pendingShareUrl = ref<Record<number, string>>({})
  const shareLoadingById = ref<Record<number, boolean>>({})

  function setShareLoading(collectionId: number, loading: boolean) {
    const next = { ...shareLoadingById.value }
    if (loading) next[collectionId] = true
    else delete next[collectionId]
    shareLoadingById.value = next
  }

  function setShareTooltipOpen(collectionId: number, open: boolean) {
    shareTooltipOpen.value = { ...shareTooltipOpen.value, [collectionId]: open }
    if (!open) {
      const next = { ...pendingShareUrl.value }
      delete next[collectionId]
      pendingShareUrl.value = next
    }
  }

  onMounted(() => {
    if (!collections.value?.length) {
      lockerRoomStore.fetchCollections()
    }
  })
  const editingIndex = ref<number | null>(null)
  const editName = ref<string>('')

  const baseStorageUrl = computed(() => import.meta.env.VITE_APP_STORAGE_URL || '')
  const computedCollections = computed(() => collections.value || [])
  const getDateValue = (value?: string) => (value ? new Date(value).getTime() : 0)

  const collectionSorters: Record<SortOption, (a: Collection, b: Collection) => number> = {
    lastModified: (a, b) => getDateValue(b.updated_at) - getDateValue(a.updated_at),
    alphabetical: (a, b) => a.name.localeCompare(b.name),
    createdDate: (a, b) => getDateValue(b.created_at) - getDateValue(a.created_at)
  }

  const sortedCollections = computed(() => {
    const sorter = collectionSorters[props.sort] || collectionSorters.lastModified
    return [...computedCollections.value].sort(sorter)
  })

  const filteredBySearch = computed(() => {
    const searchTerm = props.search?.toLowerCase().trim()
    if (!searchTerm) return sortedCollections.value
    return sortedCollections.value.filter(collection =>
      collection.name.toLowerCase().includes(searchTerm)
    )
  })

  const filteredCollections = computed(() => {
    const list = filteredBySearch.value
    if (collectionFilter.value === 'all') return list
    if (collectionFilter.value === 'autoGenerated') return list.filter(c => !!c.room_id)
    return list.filter(c => !c.room_id)
  })

  function getCollectionShareUrl(collection: Collection): string | null {
    const link = collection.link || collection.shared_url
    if (!link) return null
    if (link.startsWith('http://') || link.startsWith('https://')) return link
    if (typeof window === 'undefined') return link
    const base = window.location.origin
    return link.startsWith('/') ? `${base}${link}` : `${base}/${link}`
  }

  async function handleShareClick(collection: Collection, event?: Event) {
    if (getCollectionShareUrl(collection)) return
    event?.preventDefault()
    event?.stopPropagation()
    if (shareLoadingById.value[collection.id]) return

    setShareLoading(collection.id, true)
    try {
      const res = await API.lockers.shareCollection(collection.id)
      const url = res.data?.result?.shared_url?.trim()
      if (url) {
        pendingShareUrl.value = { ...pendingShareUrl.value, [collection.id]: url }
        lockerRoomStore.setCollectionShareUrl(collection.id, url)
        shareTooltipOpen.value[collection.id] = true
      } else {
        toast.error(msg_failed_to_generate_share_url({}, { locale: locale.value }), {
          position: 'top-right',
          richColors: true
        })
      }
    } catch {
      toast.error(msg_failed_to_generate_share_url({}, { locale: locale.value }), {
        position: 'top-right',
        richColors: true
      })
    } finally {
      setShareLoading(collection.id, false)
    }
  }

  function handleDownloadPdf(collection: Collection, event?: Event) {
    event?.preventDefault()
    event?.stopPropagation()
    const path = collection.pdf_link
    if (!path) return
    const url =
      path.startsWith('http://') || path.startsWith('https://')
        ? path
        : `${baseStorageUrl.value.replace(/\/+$/, '')}/${path.replace(/^\/+/, '')}`
    const filename = collection.file_name
      ? `${collection.file_name}.pdf`
      : `collection-${collection.id}.pdf`
    downloadFromUrl(url, filename)
  }

  async function handleDeleteCollection(collection: Collection, event?: Event) {
    event?.preventDefault()
    event?.stopPropagation()
    const ok = await confirmDialog({
      title: locker_delete_collection_confirm({}, { locale: locale.value }),
      description: locker_action_cannot_undo({}, { locale: locale.value })
    })
    if (ok) {
      await lockerRoomStore.deleteCollection(collection.id)
    }
  }

  const timeAgoMessages = computed(() => ({
    just_now: () => time_ago_just_now({}, { locale: locale.value }),
    seconds: (params: { count: number }) => time_ago_seconds(params, { locale: locale.value }),
    seconds_plural: (params: { count: number }) =>
      time_ago_seconds_plural(params, { locale: locale.value }),
    minutes: (params: { count: number }) => time_ago_minutes(params, { locale: locale.value }),
    minutes_plural: (params: { count: number }) =>
      time_ago_minutes_plural(params, { locale: locale.value }),
    hours: (params: { count: number }) => time_ago_hours(params, { locale: locale.value }),
    hours_plural: (params: { count: number }) =>
      time_ago_hours_plural(params, { locale: locale.value }),
    days: (params: { count: number }) => time_ago_days(params, { locale: locale.value }),
    days_plural: (params: { count: number }) =>
      time_ago_days_plural(params, { locale: locale.value }),
    yesterday: () => time_ago_yesterday({}, { locale: locale.value }),
    months: (params: { count: number }) => time_ago_months(params, { locale: locale.value }),
    months_plural: (params: { count: number }) =>
      time_ago_months_plural(params, { locale: locale.value }),
    years: (params: { count: number }) => time_ago_years(params, { locale: locale.value }),
    years_plural: (params: { count: number }) =>
      time_ago_years_plural(params, { locale: locale.value })
  }))

  const localizedTimeAgo = (dateTime: string) => timeAgo(dateTime, timeAgoMessages.value)

  function createCollection() {
    isCreatingCollection.value = true
  }
  // const saveCollection = async () => {
  //   if (!room_name.value) return
  //   // await lockerRoomStore.createCollection(room_name.value as string)
  //   isCreatingCollection.value = false
  //   room_name.value = undefined
  // }

  async function saveEdit(collection: any) {
    if (!editName.value.length) return
    // Don't allow editing name if collection has room_id
    if (collection.room_id) return

    // Update collection name through store
    const formData = new FormData()
    formData.append('name', editName.value)
    formData.append('_method', 'PUT')
    const ok = await lockerRoomStore.updateCollection(collection.id, formData)
    if (!ok) return

    editingIndex.value = null
    editName.value = ''
  }

  function startEdit(index: number, collection: any) {
    // Don't allow editing if collection has room_id
    if (collection.room_id) return
    editingIndex.value = index
    editName.value = collection.name
  }

  function cancelEdit() {
    editingIndex.value = null
    editName.value = ''
  }
  defineExpose({ createCollection })
</script>

<template>
  <Spinner v-if="isLoading" class="size-8 text-primary m-auto mb-4" />
  <div v-else data-testid="locker-room-collection-list" class="grid grid-cols-1 gap-6 relative group">
    <!-- Filter buttons -->
    <div class="flex flex-wrap gap-2 mb-4">
      <Button
        :variant="collectionFilter === 'all' ? 'primary' : 'outline'"
        size="sm"
        @click="collectionFilter = 'all'"
      >
        All
      </Button>
      <Button
        :variant="collectionFilter === 'autoGenerated' ? 'primary' : 'outline'"
        size="sm"
        @click="collectionFilter = 'autoGenerated'"
      >
        Auto generated
      </Button>
      <Button
        :variant="collectionFilter === 'custom' ? 'primary' : 'outline'"
        size="sm"
        @click="collectionFilter = 'custom'"
      >
        Custom
      </Button>
    </div>

    <EmptyState
      v-if="filteredCollections.length === 0"
      title="Nothing found"
      description="No collections match your search or filter. Try a different search term or filter."
    />

    <template v-else>
      <Card
        v-for="(collection, collectionIndex) in filteredCollections"
        :key="collection.id"
        class="group rounded-lg cursor-pointer md:py-0 p-0 bg-transparent relative gap-2! h-fit duration-150 border-0 flex flex-row"
        @click="emit('open-collection', collection)"
      >
        <div
          class="bg-secondary rounded-md md:aspect-video flex justify-center items-center overflow-hidden gap-1 place-items-start p-[10px] border relative"
        >
          <template v-if="collection.collection_thumbnails.length">
            <div class="w-[156px] flex justify-center">
              <AvatarQueue
                :size="'60'"
                :images="
                  collection.collection_thumbnails
                    .slice(0, 3)
                    .map(thumbnail => baseStorageUrl + thumbnail.front_url)
                "
                :max="3"
                :class="'overflow-hidden mr-2'"
                :avatar-class="'!rounded-[13px] border-0 !ring-0 !bg-transparent !shadow-none '"
              />
            </div>
          </template>
          <template v-else>
            <div class="w-[156px] flex justify-center">
              <img
                :src="PLACEHOLDER_IMAGE"
                class="h-full overflow-hidden object-contain rounded-md w-full"
              />
            </div>
          </template>
        </div>

        <!-- Edit Mode -->
        <div
          v-if="editingIndex === collectionIndex"
          class="metadata flex gap-2 pt-2 items-center"
          @click.stop
        >
          <Input
            v-model="editName"
            :placeholder="locker_name_placeholder({}, { locale })"
            class="flex-1"
          />

          <ButtonGroup>
            <Button variant="primary" size="default" @click.stop="saveEdit(collection)">
              <Check class="size-4" />
            </Button>

            <Button size="default" variant="secondary" @click.stop="cancelEdit">
              <X class="size-4" />
            </Button>
          </ButtonGroup>
        </div>

        <!-- Normal Metadata -->
        <div
          v-else
          class="metadata flex flex-col justify-center flex-1 min-w-0"
          @click.stop="emit('open-collection', collection)"
        >
          <div
            class="flex flex-col md:flex-row items-start md:items-center justify-between gap-2 w-full"
          >
            <div class="min-w-0 flex-1">
              <div
                class="mt-2 text-base font-medium"
                :class="{ 'cursor-text': !collection.room_id }"
                @dblclick.stop="startEdit(collectionIndex, collection)"
              >
                {{ collection.name }}
              </div>
              <div
                class="text-xs md:text-sm text-muted-foreground flex gap-[0.5] md:gap-1 items-center flex-wrap"
              >
                <span class="flex items-center gap-1">
                  <ShoppingBag class="size-3.5 inline-block" />
                  {{ collection.collection_products_count || 0 }}
                  {{ locker_designs_count({}, { locale }) }}
                </span>
                <DotSeparator class="bg-muted-foreground" />
                <span class="flex items-center gap-1">
                  <Calendar class="size-3.5 inline-block" />
                  {{ localizedTimeAgo(collection.updated_at) }}
                </span>
                <template v-if="collection.room_id">
                  <DotSeparator class="bg-muted-foreground" />
                  <TooltipProvider>
                    <Tooltip>
                      <TooltipTrigger>
                        <span class="flex items-center gap-1">
                          <InfoIcon class="size-3.5 inline-block" />
                          {{ locker_auto_generated({}, { locale }) }}
                        </span>
                      </TooltipTrigger>
                      <TooltipContent>{{
                        locker_auto_generated_tooltip({}, { locale })
                      }}</TooltipContent>
                    </Tooltip>
                  </TooltipProvider>
                </template>
              </div>
            </div>
            <div class="flex items-center gap-1 shrink-0" @click.stop>
              <ShareUrlTooltip
                :share-url="pendingShareUrl[collection.id] ?? getCollectionShareUrl(collection)"
                :open="shareTooltipOpen[collection.id] || false"
                @update:open="setShareTooltipOpen(collection.id, $event)"
              >
                <Button
                  variant="outline"
                  size="sm"
                  class="h-8"
                  :disabled="!!shareLoadingById[collection.id]"
                  @click="handleShareClick(collection, $event)"
                >
                  <Loader2
                    v-if="shareLoadingById[collection.id]"
                    class="w-3.5 h-3.5 mr-1 animate-spin"
                  />
                  <Share2 v-else class="w-3.5 h-3.5 mr-1" />
                  Share
                </Button>
              </ShareUrlTooltip>
              <Button
                variant="outline"
                size="sm"
                class="h-8"
                :disabled="!collection.pdf_link"
                @click="handleDownloadPdf(collection, $event)"
              >
                <FileDown class="w-3.5 h-3.5 mr-1" />
                Download PDF
              </Button>
              <DropdownMenu v-if="!collection.room_id">
                <DropdownMenuTrigger as-child>
                  <Button variant="outline" size="icon" class="h-8 w-8">
                    <MoreVertical class="w-4 h-4" />
                  </Button>
                </DropdownMenuTrigger>
                <!-- <DropdownMenuPortal to="body"> -->
                <DropdownMenuContent class="w-40 z-widget-dialog">
                  <DropdownMenuItem
                    class="cursor-pointer text-destructive focus:text-destructive"
                    @click="handleDeleteCollection(collection, $event)"
                  >
                    <Trash2 class="size-4 mr-2" />
                    Delete
                  </DropdownMenuItem>
                </DropdownMenuContent>
                <!-- </DropdownMenuPortal> -->
              </DropdownMenu>
            </div>
          </div>
        </div>
      </Card>
    </template>
  </div>
</template>
