/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IFlexFlatPaintPalette: typeof import('~icons/flex-flat/paint-palette')['default']
    IFlexLineAiEditSpark: typeof import('~icons/flex-line/ai-edit-spark')['default']
    IFlexLineAiSparkles: typeof import('~icons/flex-line/ai-sparkles')['default']
    IFlexLineCart: typeof import('~icons/flex-line/cart')['default']
    IFlexLineCategories: typeof import('~icons/flex-line/categories')['default']
    IFlexLineDelete: typeof import('~icons/flex-line/delete')['default']
    IFlexLineEdit: typeof import('~icons/flex-line/edit')['default']
    IFlexLineGridView: typeof import('~icons/flex-line/grid-view')['default']
    IFlexLineLandscape1: typeof import('~icons/flex-line/landscape1')['default']
    IFlexLineListView: typeof import('~icons/flex-line/list-view')['default']
    IFlexLinePaintPalette: typeof import('~icons/flex-line/paint-palette')['default']
    IFlexLinePattern: typeof import('~icons/flex-line/pattern')['default']
    IFlexLineReorder: typeof import('~icons/flex-line/reorder')['default']
    IFlexLineSave: typeof import('~icons/flex-line/save')['default']
    IFlexLineShare: typeof import('~icons/flex-line/share')['default']
    IFlexLineTable: typeof import('~icons/flex-line/table')['default']
    IFlexLineTextFile: typeof import('~icons/flex-line/text-file')['default']
    IFlexLineTextStyle: typeof import('~icons/flex-line/text-style')['default']
    IOtherImage: typeof import('~icons/other/image')['default']
    IOtherWarrantyBadgeHighlight: typeof import('~icons/other/warranty-badge-highlight')['default']
  }
}
