export { default as MenuPanel } from './MenuPanel.vue'
export { default as CategoryPanel } from './CategoryPanel.vue'
export { default as ProductPanel } from './ProductPanel.vue'
export { default as DesignsPanel } from './DesignsPanel.vue'
export { default as StylesPanel } from './StylesPanel.vue'
export { default as LogosPanel } from './logos/LogosPanel.vue'
