export type LogosSubStep = 'list' | 'placement' | 'edit'
export type ProductsSubStep = 'category' | 'subcategory' | 'product'
export type PatternsSubStep = 'list' | 'group'
export type TextsSubStep = 'list' | 'placement'
export type RosterSubStep = 'list' | 'edit'
export type CanvasSide = 'front' | 'back'
