export type LogosSubStep = 'list' | 'placement' | 'edit'
export type ProductsSubStep = 'category' | 'subcategory' | 'product'
export type PatternsSubStep = 'list' | 'edit'
export type TextsSubStep = 'list' | 'placement'
export type RosterSubStep = 'list' | 'edit'
export type CanvasSide = 'front' | 'back'
export type CustomizerStep =
  | 'product'
  | 'designs'
  | 'styles'
  | 'logos'
  | 'colors'
  | 'patterns'
  | 'texts'
  | 'roster'
  | 'summary'
