/* eslint-disable @typescript-eslint/no-explicit-any */
import { mount, type MountingOptions } from '@vue/test-utils'
import { createTestingPinia, type TestingOptions } from '@pinia/testing'
import { createMemoryHistory, createRouter, type RouteRecordRaw } from 'vue-router'
import { vi, type Mock } from 'vitest'
import type { Component } from 'vue'

// ---------------------------------------------------------------------------
// Paraglide i18n stubs
// Any function imported from `@/paraglide/messages` follows the signature:
//   (params?: Record<string, unknown>, options?: { locale?: string }) => string
// We replace the entire module with a vi.mock at the test level, but here we
// expose a factory so individual tests can supply specific return values.
// ---------------------------------------------------------------------------

/** Returns a vi.fn() that echoes the message key (last path segment) as a string. */
export function makeMessageStub(key: string): Mock {
  return vi.fn(() => key)
}

// ---------------------------------------------------------------------------
// Default minimal routes – mirrors the real router's shape but avoids
// dynamic imports that would pull in canvas/three heavy components.
// ---------------------------------------------------------------------------
const defaultRoutes: RouteRecordRaw[] = [
  {
    path: '/',
    component: { template: '<div />' }
  },
  {
    path: '/:pathMatch(.*)*',
    component: { template: '<div />' }
  }
]

export interface MountWithProvidersOptions {
  /** Additional / override routes for this test. */
  routes?: RouteRecordRaw[]
  /** Forwarded directly to createTestingPinia. */
  piniaOptions?: TestingOptions
  /** Any extra mounting options forwarded to @vue/test-utils mount. */
  mountOptions?: MountingOptions<any>
}

/**
 * Mounts a component with a real (but memory-backed) Vue Router and a
 * @pinia/testing Pinia. Avoids any network calls or DOM side-effects that
 * come from the real bootstrap.ts.
 *
 * @example
 * ```ts
 * const wrapper = await mountWithProviders(MyComponent, {
 *   piniaOptions: { initialState: { myStore: { count: 5 } } }
 * })
 * expect(wrapper.find('[data-testid="my-root"]').exists()).toBe(true)
 * ```
 */
export async function mountWithProviders(
  component: Component,
  options: MountWithProvidersOptions = {}
) {
  const { routes = defaultRoutes, piniaOptions = {}, mountOptions = {} } = options

  const router = createRouter({
    history: createMemoryHistory(),
    routes
  })

  const pinia = createTestingPinia({
    createSpy: vi.fn,
    stubActions: false,
    ...piniaOptions
  })

  const wrapper = mount(component as any, {
    global: {
      plugins: [pinia, router],
      stubs: {
        // Stub icon components generated by unplugin-icons so tests don't
        // need to resolve the SVG file-system loaders.
        'i-flex-line-categories': { template: '<span />' },
        'i-flex-line-ai-edit-spark': { template: '<span />' },
        'i-flex-line-ai-sparkles': { template: '<span />' },
        'i-flex-line-landscape1': { template: '<span />' },
        'i-flex-line-paint-palette': { template: '<span />' },
        'i-flex-line-pattern': { template: '<span />' },
        'i-flex-line-text-style': { template: '<span />' },
        'i-flex-line-table': { template: '<span />' },
        'i-flex-line-text-file': { template: '<span />' }
      },
      ...mountOptions.global
    },
    ...mountOptions
  })

  // Wait for the router to be ready before returning so async navigation
  // guards don't race with assertions.
  await router.isReady()

  return wrapper
}
